builds:
  -
    id: pixela-desktop
    env:
      - CGO_ENABLED=0
    main: main.go
    binary: pixela-desktop
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=nucular_shiny
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "pixela-desktop_{{.Os}}_{{.Arch}}"
    format: zip
    format_overrides:
      - goos: linux
        format: tar.gz
checksum:
  name_template: 'checksums.txt'
