name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: v1-${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            v1-${{ runner.os }}-gomod-
      - name: dep
        run: go mod download
      - name: mock file for statik
        run: |
          mkdir -p fonts
          touch fonts/dummy.ttf
          go get github.com/rakyll/statik
          $(go env GOPATH)/bin/statik -f -include=*.ttf -src=fonts
      - name: test
        run: go test -v -cover ./...
